### ISSUE TITLE
支付完成 不回调

### ISSUE THREAD

**Issue by wcxdandan** [YClimb/wxpay-sdk#6]
![image](https://user-images.githubusercontent.com/59184784/93866511-55385480-fcfa-11ea-8af9-4ed64383933d.png)
支付完成不回调  怎么解决呢

**Comment by wcxdandan** [comment]
![Uploading image.png…]()

**Comment by YClimb** [comment]
1.检查自己统一下单接口是否传入地址，或者商户后台是否配置
2.检查地址是否外网可访问，是否符合微信文档要求的标准
